node:
  hostname: 'vm1'
  
minecraft:
  gamemode: 'survival'
  motd: 'my-mc-pod-1' 
  internal_port: 25565
  exposed_port: 30001

volume:
  storage: 3Gi
  path: '/tmp/workspace/minecraft-data'

resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "2000m"
    memory: "3Gi"

serviceAccount:
  create: true