apiVersion: v1
kind: Service
metadata:
  name: {{ printf "minecraft-server-%s" .Values.minecraft.motd }}
  namespace: minecraft
  labels:
    app: {{ printf "minecraft-server-%s" .Values.minecraft.motd }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.minecraft.internal_port }}
      nodePort: {{ .Values.minecraft.exposed_port }}
  selector:
    app: {{ printf "minecraft-server-%s" .Values.minecraft.motd }}
