apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: minecraftservers.minecraft.example.com
spec:
  group: minecraft.example.com
  names:
    kind: MinecraftServer
    plural: minecraftservers
    singular: minecraftserver
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                server-name:
                  type: string
                player-count:
                  type: int
